server:
  port: 8082
  session:
    timeout: 172800
spring:
  application:
    name: hestia
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/news?useUnicode=true&characterEncoding=utf-8
    username: news
    password: news
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      initial-size: 5
      max-idle: 5
      max-total: 20
      min-idle: 3
      validation-query: select 1
      test-on-borrow: true
      test-while-idle: true
      test-on-return: false
      max-wait-millis: 10000
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
    database: mysql
    generate-ddl: true
    show-sql: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
